kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: sandbox-oz
  name: sandbox-for-oz
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # You can also use ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: sandbox-for-oz-binding
  namespace: sandbox-oz
subjects:
- kind: User
  name: dago
  apiGroup: ""
roleRef:
  kind: Role
  name: sandbox-for-oz
  apiGroup: ""